print 'I am sailing'
print 'home again' 
print 'cross the sea'
print 'I am sailing'
print 'stormy waters'
print 'to be near you'
print 'to be free'
print 'I am flying'
print 'I am flying'
print 'Stewart Rodlike a bird cross the sky'
print 'I am flying'
print 'passing high clouds'
print 'to be with you'
print 'to be free.Can you hear me'
print 'can you hear methro the dark night'
print 'far away'
print 'I am dying'
print 'forever trying'
print 'to be with you'
print 'who can say'
print 'thro the dark night far away'
print 'I am dying'
print 'forever trying'
print 'to be with you'
print 'who can say'
print 'We are sailing we are sailing,home again cross the sea'
print 'We are sailing stormy waters'
print 'to be near you'
print ' to be free'
print 'Oh Lord'
print 'to be near you'
print 'to be free'
print 'Oh Lord'
print ' to be near you'
print ' to be free'
print 'Oh Lord'